/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.winestores.views;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import lk.ijse.winestores.views.util.CashTendered;

/**
 *
 * @author Ranjith Suranga
 */
public class CashTenderForm extends javax.swing.JFrame {

    private SuraButton sbtn;
    private BigDecimal total;
    
    private CashTendered owner;
    
    public CashTenderForm(CashTendered owner, BigDecimal total) {
        initForm();
        
        this.owner = owner;
        this.setTotal(total);
    }

    private void initForm() {
        initComponents();
        
        sbtn = new SuraButton(pnlContainer);
        sbtn.convertAllJButtonsToSuraButtons();
        
        lblBalance.setText("-");
        btnPlaceOrder.setEnabled(false);

        pnlContainer.setVisible(false);
        setExtendedState(MAXIMIZED_BOTH);
        setBackground(new Color(0, 0, 0, 200));

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {

                Point p = new Point();
                p.x = (CashTenderForm.this.getWidth() - pnlContainer.getWidth()) / 2;
                p.y = (CashTenderForm.this.getHeight() - pnlContainer.getHeight()) / 2;
                pnlContainer.setLocation(p);
                
                p.x = p.x + pnlContainer.getWidth() - lblClose.getWidth() -10;
                p.y -= 20;
                lblClose.setLocation(p);
                
                pnlContainer.setVisible(true);
                
                txtCashTendered.requestFocusInWindow();
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClose = new javax.swing.JLabel();
        pnlContainer = new javax.swing.JPanel(){
            public void paintComponent(Graphics g) {
                //To change body of generated methods, choose Tools | Templates.
                Graphics2D gd = (Graphics2D)g;
                gd.setColor(pnlContainer.getBackground());
                gd.fillRoundRect(0, 0, pnlContainer.getWidth(), pnlContainer.getHeight(), 10, 10);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtCashTendered = new javax.swing.JTextField();
        lblBalance = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/winestores/icons/close.png"))); // NOI18N
        lblClose.setToolTipText("Close");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        getContentPane().add(lblClose);
        lblClose.setBounds(570, 10, 50, 40);

        pnlContainer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        jLabel1.setText("Total :");

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        jLabel2.setText("Cash Tendered :");

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        jLabel3.setText("Balance :");

        lblTotal.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 204, 0));
        lblTotal.setText("123.12");

        txtCashTendered.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        txtCashTendered.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCashTenderedKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCashTenderedKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCashTenderedKeyTyped(evt);
            }
        });

        lblBalance.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(255, 0, 0));
        lblBalance.setText("123.12");

        btnPlaceOrder.setBackground(new java.awt.Color(72, 158, 231));
        btnPlaceOrder.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.setToolTipText("Click to fnish the order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCashTendered)
                    .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlContainerLayout.createSequentialGroup()
                        .addComponent(btnPlaceOrder)
                        .addGap(0, 104, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCashTendered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblBalance))
                .addGap(18, 18, 18)
                .addComponent(btnPlaceOrder)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(pnlContainer);
        pnlContainer.setBounds(10, 30, 650, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.dispose();
    }//GEN-LAST:event_formMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void txtCashTenderedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashTenderedKeyTyped
        
        if (!(Character.isDigit(evt.getKeyChar())
                || evt.getKeyChar() == KeyEvent.VK_DELETE
                || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE
                || evt.getKeyChar() == KeyEvent.VK_PERIOD)) {

            evt.consume();
            
        } else {

            String currentPrice = txtCashTendered.getText();

            if (currentPrice.contains(".") && evt.getKeyChar() == KeyEvent.VK_PERIOD) {
                if (txtCashTendered.getSelectedText() == null) {
                    evt.consume();
                }
            }

        }
    }//GEN-LAST:event_txtCashTenderedKeyTyped

    private void txtCashTenderedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashTenderedKeyReleased
       
       if (txtCashTendered.getText().isEmpty()){
           btnPlaceOrder.setEnabled(false);
           return;
       }
       
       BigDecimal tenderedCash = new BigDecimal(txtCashTendered.getText());
       BigDecimal balance = tenderedCash.subtract(total).setScale(2,RoundingMode.HALF_UP);
       
       if (balance.compareTo(BigDecimal.ZERO) > 0 ){
           lblBalance.setText(balance.toPlainString());
           btnPlaceOrder.setEnabled(true);
       }else{
           lblBalance.setText("-");
           btnPlaceOrder.setEnabled(false);           
       }
       
    }//GEN-LAST:event_txtCashTenderedKeyReleased

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        
        BigDecimal cashTendered = new BigDecimal(txtCashTendered.getText());
        owner.processOrder(cashTendered.setScale(2,RoundingMode.HALF_UP));
        this.dispose();
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void txtCashTenderedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashTenderedKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnPlaceOrder.doClick();
        }
    }//GEN-LAST:event_txtCashTenderedKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JTextField txtCashTendered;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the total
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * @param total the total to set
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
        lblTotal.setText(total.setScale(2).toPlainString());
    }
}
