/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.winestores.views;

import lk.ijse.winestores.views.util.Extension;

/**
 *
 * @author Ranjith Suranga
 */
public class ReportContainer extends javax.swing.JPanel implements Extension{
    
    private String extenstionName;

    /**
     * Creates new form ReportContainer
     */
    public ReportContainer(String extenstionName) {
        initComponents();
        this.extenstionName = extenstionName;
    }

//    @Override
//    public Component add(Component comp) {
//        Component addedCmp = super.add(comp); 
//        this.updateUI();
//        return addedCmp;
//    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean exit() {
        return true;
    }

    @Override
    public String getExtensionName() {
        return this.extenstionName;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
