/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.winestores.views;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ranjith Suranga
 */
public class SearchCreditOrderSearchPanel extends javax.swing.JPanel {

    private JButton btnSearch;

    /**
     * Creates new form SearchCreditOrderSearchPanel
     */
    public SearchCreditOrderSearchPanel(JButton btnSearch) {
        initComponents();

        this.btnSearch = btnSearch;

        dtFrom.getEditor().addKeyListener(new KeyAdapter() {

            @Override
            public void keyTyped(KeyEvent e) {
                super.keyTyped(e);

                if (e.getKeyChar() == KeyEvent.VK_ENTER) {
                    dtTo.requestFocusInWindow();
                }
            }

        });

        dtTo.getEditor().addKeyListener(new KeyAdapter() {

            @Override
            public void keyTyped(KeyEvent e) {
                super.keyTyped(e);

                if (e.getKeyChar() == KeyEvent.VK_ENTER) {
                    try {
                        dtTo.commitEdit();
                        btnSearch.doClick();                        
                    } catch (ParseException ex) {
                        dtTo.getEditor().selectAll();
//                        Logger.getLogger(SearchCreditOrderSearchPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dtFrom = new org.jdesktop.swingx.JXDatePicker();
        dtTo = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(255, 255, 255));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel1.setText("From : ");

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel2.setText("To :");

        dtFrom.setDate(new Date());
        dtFrom.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        dtFrom.setFormats(new SimpleDateFormat
            ("yyyy-MM-dd"));
        dtFrom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dtFromFocusGained(evt);
            }
        });
        dtFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtFromActionPerformed(evt);
            }
        });
        dtFrom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dtFromKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dtFromKeyTyped(evt);
            }
        });

        dtTo.setDate(new Date());
        dtTo.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        dtTo.setFormats(new SimpleDateFormat
            ("yyyy-MM-dd"));
        dtTo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dtToFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dtFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dtTo, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dtFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtFromActionPerformed

    private void dtFromKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dtFromKeyTyped

    }//GEN-LAST:event_dtFromKeyTyped

    private void dtFromKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dtFromKeyPressed

    }//GEN-LAST:event_dtFromKeyPressed

    private void dtFromFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dtFromFocusGained
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                dtFrom.getEditor().selectAll();
            }
        });
    }//GEN-LAST:event_dtFromFocusGained

    private void dtToFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dtToFocusGained
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                dtTo.getEditor().selectAll();
            }
        });
    }//GEN-LAST:event_dtToFocusGained

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
    }//GEN-LAST:event_formFocusGained

    public Date getFromDate() {
        return dtFrom.getDate();
    }

    public Date getToDate() {
        return dtTo.getDate();
    }

    public void focusFromDate() {
        dtFrom.requestFocusInWindow();
    }

    public void focusToDate() {
        dtTo.requestFocusInWindow();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dtFrom;
    private org.jdesktop.swingx.JXDatePicker dtTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
