/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.winestores.views;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import lk.ijse.winestores.resource.ResourceConnection;
import lk.ijse.winestores.resource.ResourceFactory;
import net.sf.jasperreports.engine.DefaultJasperReportsContext;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRPropertiesUtil;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Ranjith Suranga
 */
public class Views extends javax.swing.JPanel {

    /**
     * Creates new form Views
     */
    public Views() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnItemMasterFullReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInitialStockTakingReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnItemMasterFullReport.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnItemMasterFullReport.setText("Item Master Full Report");
        btnItemMasterFullReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemMasterFullReportActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/winestores/images/under-construction.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/winestores/images/animated-working-on-it.gif"))); // NOI18N

        btnInitialStockTakingReport.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnInitialStockTakingReport.setText("Initial Stock Taking Report");
        btnInitialStockTakingReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitialStockTakingReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnItemMasterFullReport, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnInitialStockTakingReport, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnItemMasterFullReport, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInitialStockTakingReport, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnItemMasterFullReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemMasterFullReportActionPerformed

        Connection connection;

        Cursor currentCursor = this.getCursor();
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        try {

            DefaultJasperReportsContext context = DefaultJasperReportsContext.getInstance();
            JRPropertiesUtil.getInstance(context).setProperty("net.sf.jasperreports.xpath.executer.factory",
                    "net.sf.jasperreports.engine.util.xml.JaxenXPathExecuterFactory");

            connection = (Connection) ResourceFactory.getInstance().getResourceConnection(ResourceConnection.ResourceConnectionType.DATABSE).getConnection();
            //JasperReport compiledReport = JasperCompileManager.compileReport(this.getClass().getResourceAsStream("/lk/ijse/winestores/reports/ItemMasterFullReport.jrxml"));
            JasperReport compiledReport = (JasperReport) JRLoader.loadObject(this.getClass().getResourceAsStream("/lk/ijse/winestores/reports/ItemMasterFullReport.jasper"));
            JasperPrint filledReport = JasperFillManager.fillReport(compiledReport, new HashMap<>(), connection);
            JRViewer pnlReport = new JRViewer(filledReport);


            Main m = (Main) SwingUtilities.getWindowAncestor(this);
            m.pnlContainer.removeAll();
            ReportContainer reportContainer = new ReportContainer("Item Master Full Report");
            m.setExtenstion(reportContainer);
            reportContainer.add(pnlReport);
            reportContainer.updateUI();
            m.pnlContainer.add(reportContainer);
            m.pnlContainer.updateUI();

            // Closing the connection
            connection.close();
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(Views.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Views.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Views.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.setCursor(currentCursor);
        }

    }//GEN-LAST:event_btnItemMasterFullReportActionPerformed

    private void btnInitialStockTakingReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitialStockTakingReportActionPerformed

        Connection connection;

        Cursor currentCursor = this.getCursor();
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        try {

            DefaultJasperReportsContext context = DefaultJasperReportsContext.getInstance();
            JRPropertiesUtil.getInstance(context).setProperty("net.sf.jasperreports.xpath.executer.factory",
                    "net.sf.jasperreports.engine.util.xml.JaxenXPathExecuterFactory");

            connection = (Connection) ResourceFactory.getInstance().getResourceConnection(ResourceConnection.ResourceConnectionType.DATABSE).getConnection();
            //JasperReport compiledReport = JasperCompileManager.compileReport(this.getClass().getResourceAsStream("/lk/ijse/winestores/reports/ItemMasterFullReport.jrxml"));
            JasperReport compiledReport = (JasperReport) JRLoader.loadObject(this.getClass().getResourceAsStream("/lk/ijse/winestores/reports/InitialStockTakingReport.jasper"));
            JasperPrint filledReport = JasperFillManager.fillReport(compiledReport, new HashMap<>(), connection);
            JRViewer pnlReport = new JRViewer(filledReport);

            Main m = (Main) SwingUtilities.getWindowAncestor(this);
            m.pnlContainer.removeAll();
            ReportContainer reportContainer = new ReportContainer("Initial Stock Taking Report");
            m.setExtenstion(reportContainer);
            reportContainer.add(pnlReport);
            reportContainer.updateUI();
            m.pnlContainer.add(reportContainer);
            m.pnlContainer.updateUI();

            // Closing the connection
            connection.close();
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(Views.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Views.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Views.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.setCursor(currentCursor);
        }        
        
        
    }//GEN-LAST:event_btnInitialStockTakingReportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInitialStockTakingReport;
    private javax.swing.JButton btnItemMasterFullReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
